export const APP_WORKING = 'APP_WORKING'
export const APP_ERROR = 'APP_ERROR'
export const BOOKING_AVAILABLE_TIME_SLOTS = 'BOOKING_AVAILABLE_TIME_SLOTS'
export const BOOKED_DATE_TIME = 'BOOKED_DATE_TIME'
